[pytest]
pythonpath = .

# all nested tests dirs
testpaths = .

# use conventions that MOST models will follow
# why? because consistency is king
# way way way before personal preferences
#
# yes I understand the irony of building this tool that is for my personal formatting preferences :)...
#
# so if you really don't care then follow the conventions
# i.e. file naming
python_files = test_*.py
